// generated by "sampctl package generate"
#include <a_samp>
#include "ChatBreaker.inc"

main() 
{
	// write tests for libraries here and run "sampctl package run"
}

public OnPlayerConnect(playerid)
{
	new 
		playername[MAX_PLAYER_NAME];
	GetPlayerName(playerid, playername, MAX_PLAYER_NAME);
	va_SendClientMessageToAll(-1, "%s has sucessfully connected to server.", playername);

	SendClientMessage(playerid, -1, "You have sucessfully connected to our server. This is an example of long string. Watch it break down.");
	return 1;
}

